### PR TITLE
Added exclusive filters

### PR DESCRIPTION
**Pull request by zhostasa**
* added parameter to allow filtration to specific packages

I need to scan only specific packages selected by arbitrary method, comments welcome.

The parameter names are terrible, but best I came up with.

If I find time I will try to add test for this specific use case.

### CODE REVIEW

**Comment by siom79** [comment]
Thank you for providing a pull request. The requirement looks a little bit specific to me, but if you really need I can merge the PR. But therefore I need some new unit tests that proof that your extension of the filters work as expected plus an enhancement of the documentation under src/site/markdown.

Thanks in advance.

**Comment by zhostasa** [comment]
I honestly have no idea if someone else does things like my team does, basically some packages contain package-info.java file which has "@public" in javadoc, which means that this package and only this package (no sub-package) is part of a public API (which is supposed to be backwards compatible between minor versions) - org.infinispan.cache is, org.infinispan.cache.impl is not. I was not able to configure japicmp to do this kind of comparison without this change.

I will look into the unit tests and documentation

**Comment by zhostasa** [comment]
Hey, this should do the job, if you see some holes in the test cases let me know.

**Comment by siom79** [comment]
Thank you for the additions. I have added you as contributor to the base pom.xml and merged the pull request.

**Comment by zhostasa** [comment]
You are welcome

**Pull request merged**
