### PR TITLE
Ant task

### PR DESCRIPTION
**Pull request by twogee**
Ant task requires the jar, so its test run as an integration test.
I didn't get it to work first, but added it as an extra commit.

### CODE REVIEW

**Comment by twogee** [comment]
I don't understand why "mvn integration-test" works locally, but fails in Travis 😢
Is it looking for a snapshot version where it's not supposed to be?

**Comment by siom79** [comment]
Thank you for providing a pull request.

The maven build fails on my machine with `Could not load 'org.apache.tools.ant.Task': org.apache.tools.ant.Task. Please make sure that all libraries have been added to the classpath (CLASSPATH=...)`. The module that fails is the maven-plugin integration test. As it looks the maven plugin is missing some ant libraries on the classpath. And the `CLASSPATH` printed out after the error message actually does not contain any ant library. It does not, because you have set the corresponding maven dependency to "provided".

That is actually the reason why I would suggest to have a separate maven module for the ant task. Otherwise you will have to change "provided" to "compile" scope and the maven plugin has ant libraries in the classpath. The same is true for all potential users of the library (like for example the gradle plugin).

**Comment by twogee** [comment]
I rebased for convenience, but Oracle JDK 7 build appears to be misconfigured

`The JAVA_HOME environment variable is not defined correctly`

**Comment by siom79** [comment]
Changes have been merged to `master` branch.

**Pull request closed without merging**
