### PR TITLE
Improved testability for Options verifikation

### PR DESCRIPTION
**Pull request by eldur**

### CODE REVIEW

**Comment by LasneF** [comment]
I would says that there is a lot of styling changes in the pull request and that should be avoided for instance new Options vs static newOptions methods, this use to be a developer pattern 

as same of source format this is highly dependent on your editor setup . 

that said adding test is good :)

**Comment by eldur** [comment]
The style changes are depended on ```.editorconfig```. Some spaces was replaced with tabs.

@siom79 What do you thing of an change what applies the style config to all files first?

**Comment by eldur** [comment]
Do you think, there is a chance to get this patchset merged?

**Comment by siom79** [comment]
Merged this changeset but made `verify()` to be non-static, as I like static factory methods like `newDefault()` (for the reasons mentioned in "Effective Java") but `verify()` should be plain old object-oriented invoked on the instance.

**Pull request merged**
