### PR TITLE
Applied .editorconfig style settings and enforced absolute imports

### PR DESCRIPTION
**Pull request by eldur**

### CODE REVIEW

**Comment by eldur** [comment]
Do you thing there is a chance to merge this change too?

**Comment by siom79** [comment]
The change set is very large and hence hard to review. Beyond that I am not pretty sure if formatting the complete code base helps much.

**Comment by eldur** [comment]
I suggested this commit to reduce the diff size for further commits.

Do you prefer commits that mixes style and code changes?

 try to diff the change with
```
git diff -w siom79/develop..e95954d | egrep -v "^[+-]import " | egrep "^[\+\-]" | egrep -v "^(\-\-\-|\+\+\+)" | egrep "^[\+\-][^\W]+"
```
or if you dislike the idea close this change unmerged

**Comment by eldur** [comment]
I've reduced the patch to fit only to the files effected by #98

**Comment by siom79** [comment]
Applied the .editorconfig myself.

**Pull request closed without merging**
