### PR TITLE
Add release workflow

### PR DESCRIPTION
**Pull request by scordio**
Once merged, the release can be triggered via [manual action](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow) under the [workflow page](https://github.com/siom79/japicmp/actions/workflows/release.yml).

The version should be set before triggering the release as no special parameter is exposed (the released version will be the one set in the POM and the next development version will have the patch number increased).

The following secrets should be added to the [repository configuration](https://github.com/siom79/japicmp/settings/secrets/actions):

* `GPG_PASSPHRASE`
* `GPG_PRIVATE_KEY`
* `OSSRH_TOKEN`
* `OSSRH_USERNAME`

### CODE REVIEW

**Comment by siom79** [comment]
I have to upload my private GPG key to github? Sounds not so good.

You have removed the profile to sign the artifacts. Where will the artifacts now get signed? Without it the OSS repository will reject them.

**Comment by scordio** [comment]
> I have to upload my private GPG key to github? Sounds not so good.

That's pretty much standard secret management, see more at https://docs.github.com/en/actions/security-guides/encrypted-secrets.

An important aspect is that GitHub uses a libsodium sealed box to help ensure that secrets are encrypted before they reach GitHub and remain encrypted until you use them in a workflow.

> You have removed the profile to sign the artifacts. Where will the artifacts now get signed? Without it the OSS repository will reject them.

That was a duplicate, already declared in the release profile: https://github.com/siom79/japicmp/blob/62c69c4d9199eaef8173841803fad2590c9046b7/pom.xml#L518-L531

**Comment by siom79** [comment]
How do I specify the version to release?

**Comment by scordio** [comment]
By default, it takes the one you have in the POM and removes the snapshot part, i.e.: 0.15.7

If you want a different version, you would need to update the POm in advance or the release workflow could be enhanced to accept parameters.

**Comment by siom79** [comment]
I have found the issue.

But it took me 10 tries to get it working. ;) The final point missing was to align the repository id in the distributionManagement of the root pom with the server-id in the release.yml. Otherwise you just get a authorization failure.

Thanks again for setting everything up.

**Comment by scordio** [comment]
Great catch and sorry for missing that!

**Pull request merged**
